# -*- mode: ruby -*-
# vi: set ft=ruby :

module OS
  def OS.windows?
    (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
  end

  def OS.mac?
   (/darwin/ =~ RUBY_PLATFORM) != nil
  end

  def OS.unix?
    !OS.windows?
  end

  def OS.linux?
    OS.unix? and not OS.mac?
  end
end

Vagrant.configure("2") do |config|

	config.vm.box = "raring64"
	config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/raring/current/raring-server-cloudimg-amd64-vagrant-disk1.box"

	config.vm.network :forwarded_port, guest: 80, host: 8989, auto_correct: true
	config.vm.network :forwarded_port, guest: 5000, host: 5000, auto_correct: true
	config.vm.network :forwarded_port, guest: 9001, host: 9001, auto_correct: true
	config.vm.network :private_network, ip: "192.168.89.90"

	if (defined?(OS.windows))
		config.vm.synced_folder "../.", "/var/www/quantumapp.co"
	else
		config.vm.synced_folder "../.", "/var/www/quantumapp.co", :nfs => true
	end

	config.vm.provider :virtualbox do |vb|
		# vb.gui = true
		vb.customize ["modifyvm", :id, "--memory", "512", "--cpuexecutioncap", "90", "--name", "quantumapp.co"]
	end

	config.vm.provision :shell, :path => "bootstrap.sh"

	config.vbguest.auto_update = false if config.respond_to?(:vbguest=)
end
